style:
  MaxLineLength:
    maxLineLength: 150

  ReturnCount:
    max: 5

  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'

complexity:
  LongParameterList:
    constructorThreshold: 15

  TooManyFunctions:
    thresholdInFiles: 16
    ignorePrivate: true

  ComplexCondition:
    threshold: 10

  LongParameterList:
    ignoreAnnotated:
      - 'Composable'

  LargeClass:
    threshold: 200
    excludes:
      - '**/src/test/**'

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
